# Generated by Django 3.0.5 on 2020-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('Lab_Tech', 'Lab Technician'), ('Lab_Sec', 'Lab Secretary'), ('Student', 'Student'), ('Staff', 'Staff')], default='Lab_Tech', max_length=30),
        ),
    ]
