# Generated by Django 3.0.5 on 2020-10-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201015_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('Lab_Tech', 'Lab Technician'), ('Lab_Sec', 'Lab Secretary'), ('Student', 'Student'), ('Staff', 'Staff')], default='Staff', max_length=30),
        ),
    ]
