# Generated by Django 3.0.5 on 2020-05-18 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_course'),
        ('users', '0003_auto_20200509_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.Course'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('Select One', 'Select One'), ('1st Year', 'First Year'), ('2nd Year', 'Second Year'), ('3rd Year', 'Third Year'), ('4th Year', 'Fourth Year'), ('5th Year', 'Fifth Year'), ('6th Year', 'Sixth Year')], default='Select One', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
    ]
