# Generated by Django 3.0.5 on 2020-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201016_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('Lab_Tech', 'Lab Technician'), ('Lab_Sec', 'Lab Secretary'), ('Lecturer', 'Lecturer'), ('Student', 'Student'), ('Staff', 'Staff')], default='Staff', max_length=30),
        ),
    ]
