# Generated by Django 3.0.5 on 2020-11-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201109_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='registration_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number'),
        ),
    ]
