# Generated by Django 3.0.5 on 2020-07-01 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_allocated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_course', to='schools.Course'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_equipment', to='equipment.Equipment'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_allocated_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
