# Generated by Django 3.0.5 on 2020-07-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('equipment', '0002_auto_20200701_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.Course'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipment.Equipment'),
        ),
    ]
