# Generated by Django 3.0.5 on 2020-06-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20200608_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.Category'),
        ),
    ]
