# Generated by Django 3.0.5 on 2020-06-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_batch_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='user',
            new_name='student',
        ),
    ]
