# Generated by Django 3.0.5 on 2020-06-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200608_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocation_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
