# Generated by Django 3.0.5 on 2020-08-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_auto_20200830_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
