# Generated by Django 3.0.5 on 2020-08-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_is_allocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
