# Generated by Django 3.0.5 on 2020-06-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_course'),
        ('equipment', '0006_auto_20200608_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_school', to='schools.School'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='equipment_quantities',
            field=models.IntegerField(default=1, verbose_name='Quantities'),
        ),
    ]
