# Generated by Django 3.0.5 on 2020-11-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_auto_20201109_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='has_exceeded_shelf_life',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='room',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
