# Generated by Django 3.0.5 on 2020-11-14 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0010_auto_20201110_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
