# Generated by Django 3.0.5 on 2020-11-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipment_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
