# Generated by Django 3.0.5 on 2020-11-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_equipment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
