# Generated by Django 3.0.5 on 2020-11-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_auto_20201116_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageunit',
            name='room',
        ),
    ]
