# Generated by Django 3.0.5 on 2020-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_remove_storageunit_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='allocating_to',
            field=models.CharField(choices=[('Student', 'Student'), ('Lecturer', 'Lecturer')], default='student', max_length=30),
        ),
    ]
