# Generated by Django 3.0.5 on 2020-05-10 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.Department'),
        ),
    ]
