# Generated by Django 3.0.5 on 2020-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20201019_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='school',
            field=models.ManyToManyField(to='schools.School'),
        ),
    ]
