# Generated by Django 3.0.5 on 2020-10-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20201019_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='school',
            field=models.ManyToManyField(related_name='labs', to='schools.School'),
        ),
    ]
