# Generated by Django 3.0.5 on 2020-11-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20201019_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='room',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
